// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkslnfleitylkwskhokp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrc2xuZmxlaXR5bGt3c2tob2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODAzNjksImV4cCI6MjA2NzA1NjM2OX0.-jcmLPpilu9fRhp6xsVAXKprYdxa0A6wuju2Zwp7R-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});